import { compareBenchmarks } from './benchmark.js';

const CHART_METRICS = [
  { key: 'downloadMbps', label: 'Download', unit: 'Mbps', higherIsBetter: true, scale: 4 },
  { key: 'uploadMbps', label: 'Upload', unit: 'Mbps', higherIsBetter: true, scale: 4 },
  { key: 'latencyMs', label: 'Latency', unit: 'ms', higherIsBetter: false, scale: 2 },
  { key: 'jitterMs', label: 'Jitter', unit: 'ms', higherIsBetter: false, scale: 8 },
  { key: 'packetLossPercent', label: 'Packet Loss', unit: '%', higherIsBetter: false, scale: 18 },
];

function escapeXml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function formatMetric(value, unit) {
  return typeof value === 'number' && Number.isFinite(value) ? `${value} ${unit}` : 'Unavailable';
}

function barWidth(value, scale) {
  if (typeof value !== 'number' || !Number.isFinite(value)) return 150;
  return Math.max(4, Math.min(260, Math.round(value * scale)));
}

function metricRow({ metric, comparison, y }) {
  const before = comparison[metric.key]?.before ?? null;
  const after = comparison[metric.key]?.after ?? null;
  const beforeClass = before === null ? 'unknown' : 'before';
  const afterClass = after === null ? 'unknown' : 'after';
  return [
    `<text x="76" y="${y + 18}" class="label">${escapeXml(metric.label)}</text>`,
    `<rect x="246" y="${y}" width="${barWidth(before, metric.scale)}" height="22" class="${beforeClass}"/>`,
    `<text x="520" y="${y + 17}" class="small">Before ${escapeXml(formatMetric(before, metric.unit))}</text>`,
    `<rect x="246" y="${y + 30}" width="${barWidth(after, metric.scale)}" height="22" class="${afterClass}"/>`,
    `<text x="520" y="${y + 47}" class="small">After ${escapeXml(formatMetric(after, metric.unit))}</text>`,
  ].join('\n  ');
}

export function generateComparisonChartSvg({ before, after, title = 'Net Boost Agent Network Report' } = {}) {
  const comparison = compareBenchmarks(before, after);
  const missingBefore = before?.metrics?.providerStatus === 'missing';
  const status = missingBefore
    ? 'Before download/upload was unavailable, so throughput improvement is inconclusive.'
    : 'Before and after benchmark data is available for comparison.';
  const rows = CHART_METRICS.map((metric, index) => metricRow({
    metric,
    comparison,
    y: 424 + index * 70,
  })).join('\n  ');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="860" viewBox="0 0 1200 860">
  <defs>
    <style>
      .bg { fill: #f7f8fb; }
      .panel { fill: #ffffff; stroke: #d7dce5; stroke-width: 1; rx: 8; }
      .title { font-family: Arial, sans-serif; font-size: 34px; font-weight: 700; fill: #172033; }
      .sub { font-family: Arial, sans-serif; font-size: 16px; fill: #5b6475; }
      .h2 { font-family: Arial, sans-serif; font-size: 22px; font-weight: 700; fill: #172033; }
      .label { font-family: Arial, sans-serif; font-size: 16px; fill: #273043; }
      .small { font-family: Arial, sans-serif; font-size: 14px; fill: #687386; }
      .metric { font-family: Arial, sans-serif; font-size: 28px; font-weight: 700; fill: #172033; }
      .before { fill: #d64545; }
      .after { fill: #12a150; }
      .unknown { fill: #c9ced8; }
      .note { fill: #fff7ed; stroke: #fed7aa; stroke-width: 1; rx: 8; }
      .noteText { font-family: Arial, sans-serif; font-size: 15px; fill: #8a4b0f; }
    </style>
  </defs>
  <rect class="bg" width="1200" height="860"/>
  <text x="48" y="58" class="title">${escapeXml(title)}</text>
  <text x="48" y="92" class="sub">Generated by Net Boost Agent</text>
  <rect x="48" y="112" width="1104" height="86" class="note"/>
  <text x="72" y="146" class="noteText">${escapeXml(status)}</text>
  <text x="72" y="174" class="noteText">Measured values are shown separately from unavailable or inconclusive metrics.</text>
  <rect x="48" y="226" width="1104" height="138" class="panel"/>
  <text x="76" y="264" class="h2">Current After Metrics</text>
  <text x="76" y="306" class="label">Download</text>
  <text x="76" y="342" class="metric">${escapeXml(after.metrics?.downloadMbps ?? 'N/A')}</text>
  <text x="176" y="342" class="small">Mbps</text>
  <text x="300" y="306" class="label">Upload</text>
  <text x="300" y="342" class="metric">${escapeXml(after.metrics?.uploadMbps ?? 'N/A')}</text>
  <text x="390" y="342" class="small">Mbps</text>
  <text x="524" y="306" class="label">Latency</text>
  <text x="524" y="342" class="metric">${escapeXml(after.metrics?.latencyMs ?? 'N/A')}</text>
  <text x="614" y="342" class="small">ms</text>
  <text x="748" y="306" class="label">Jitter</text>
  <text x="748" y="342" class="metric">${escapeXml(after.metrics?.jitterMs ?? 'N/A')}</text>
  <text x="824" y="342" class="small">ms</text>
  <text x="972" y="306" class="label">Loss</text>
  <text x="972" y="342" class="metric">${escapeXml(after.metrics?.packetLossPercent ?? 'N/A')}%</text>
  <rect x="48" y="394" width="1104" height="398" class="panel"/>
  <text x="76" y="408" class="h2">Before vs After</text>
  ${rows}
  <rect x="76" y="760" width="12" height="12" class="before"/>
  <text x="96" y="771" class="small">Before</text>
  <rect x="170" y="760" width="12" height="12" class="after"/>
  <text x="190" y="771" class="small">After</text>
  <rect x="250" y="760" width="12" height="12" class="unknown"/>
  <text x="270" y="771" class="small">Unavailable</text>
</svg>
`;
}
